import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <header className="p-4">
          <h1 style={{ fontFamily: "Electroharmonix" }}>
            Japanese Card Generator
          </h1>
        </header>
        {children}
      </body>
    </html>
  );
}
